version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      VIRTUAL_HOST: rabbit.local.management
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: smart-ranking
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq
    networks:
      - my-networks
    command: ["rabbitmq-server"]
    # command: ["bash", "-c", "rabbitmqctl add_vhost smart-ranking"]

  # smart-ranking:
  #   build: .
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     DB_CONNECT_RABBITMQ: amqp://guest:guest@rabbitmq
  #     DB_CONNECT_RABBITMQ_VHOST: smart-ranking
  #   networks:
  #     - my-networks
  #   links:
  #     - rabbitmq
  #   depends_on:
  #     - rabbitmq

  localstack:
    image: localstack/localstack
    container_name: localstack
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1
      - DEBUG=1
    ports:
      - "4566:4566" # Porta para o serviço S3 do localstack
    volumes:
      - "/tmp/localstack:/tmp/localstack"
    networks:
      - my-networks
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
      
networks:
  my-networks:
    driver: bridge
