version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      VIRTUAL_HOST: rabbit.local.management
      RABBITMQ_DEFAULT_VHOST: smart-ranking
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      # - ./rabbitmq-data:/var/lib/rabbitmq
      - ./rabbitmq-data:/temp/rabbitmq/data
    networks:
      - privateNetwork
    command: ["rabbitmq-server"]

  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - S3_PORT=4566
    ports:
      - "4566:4566"
    volumes:
      - ./localstack/data:/tmp/localstack/data
    networks:
      - privateNetwork 
  
  aws-cli:
    image: amazon/aws-cli
    depends_on:
      - localstack
    networks:
      - privateNetwork
    entrypoint: sh
    command: >
      -c "sleep 5 && \ 
      aws configure set aws_access_key_id access_key_id_default && \ 
      aws configure set aws_secret_access_key secret_access_key_default && \ 
      aws --endpoint-url=http://localstack:4566 s3api create-bucket --bucket smart-ranking-bucket"

  # smart-ranking:
  #   build: .
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     - DB_CONNECT_RABBITMQ=amqp://guest:guest@rabbitmq
  #     - DB_CONNECT_RABBITMQ_VHOST=smart-ranking
  #     - AWS_S3_ENDPOINT=http://localstack:4566
  #   networks:
  #     - privateNetwork
  #   links:
  #     - rabbitmq
  #     - localstack
  #   depends_on:
  #     - init-services
      
networks:
  privateNetwork:
    driver: bridge
