version: '3'

services:
  rabbit:
    image: rabbitmq:3-management
    container_name: rmq
    environment:
      VIRTUAL_HOST: rabbit.local.management
      DB_USERNAME: guest
      DB_PASSWORD: guest
    ports:
      - "5672:5672"
      - "15672:15672"